<a href="https://colab.research.google.com/github/EIleven/NeuralNetworks/blob/main/Tensors_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

# https://github.com/mrdbourke/pytorch-deep-learning

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.0+cu116


# INTRODUÇÃO AOS TENSORS

# Criando Tensors

https://pytorch.org/docs/stable/tensors.html

Pytorch tensors são criados usando 'torch.Tensor()'

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Trazendo o Tensor como um Python (tipo) Inteiro 
scalar.item()

7

In [ ]:
# Vetor
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIZ

MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR = torch.tensor([[[0, 11, 2],
                          [3, 4, 5], 
                          [6, 7, 8]]])
TENSOR

tensor([[[ 0, 11,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]]])

# TENSORS RANDÔMICOS 

Tensores randômicos são importântes pois o modo como muitas redes neurais aprendem paretem inicialmente de tensores repletos de números aleatórios, posteriormente ajustando estes  números aleatórios em uma melhor representação do dado.

'Começando com números randômicos - > Visualizar a informação -> atualização dos números aleatóreos -> Vizualizar a informação -> Atualização de números aleatóreos' 

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [36]:
# Criar um tensor aleatóreo de tamanho (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1795, 0.5393, 0.6450, 0.5380],
        [0.6384, 0.9504, 0.1157, 0.8714],
        [0.0924, 0.8380, 0.5367, 0.9178]])

In [13]:
# Qual é a Dimensão de random_tensor? USAMOS NDIM
random_tensor.ndim

2

In [17]:
# Criando um tensor aleatóreo com a forma de um tensor de imagem
random_image_size_tensor = torch.rand(size=( 224, 224, 3)) # Largura, altura, cores (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [24]:
# Exercício criar um tensor aleatório e de quaalquer dimensão

tensor_aleatoreo = torch.rand(2, 2)
tensor_aleatoreo

tensor([[0.1657, 0.9579],
        [0.6300, 0.9340]])

In [27]:
torch.rand(3, 3)

tensor([[0.1637, 0.7476, 0.8195],
        [0.4317, 0.7677, 0.4536],
        [0.9659, 0.8464, 0.7035]])

## TENSORES - ZEROS E UNS

In [30]:
# Criando tensor de somente zeros
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
# Multiplicando o tensor "zero" por algum "random_tensor"
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
# Criando tensor de somente uns

one = torch.ones(size=(3, 4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
one*random_tensor

tensor([[0.1795, 0.5393, 0.6450, 0.5380],
        [0.6384, 0.9504, 0.1157, 0.8714],
        [0.0924, 0.8380, 0.5367, 0.9178]])

In [38]:
# Qual é o tipo de dado do tensor "one" -> Usamos o dtype

In [39]:
one.dtype

torch.float32

# Criando um espectro de tensors e tensors semelhantes

In [52]:
# Usamos o "torch.arange()"
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# Criando tensors like (Replicando um formato)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])